name: centoire
root: <%= ENV["PWD"] %>
startup_window: control

windows:
  - backend:
      layout: even-horizontal
      panes:
        - core-api:
          - make backend
        - jobs-api:
          - make jobs-api

  - ui:
      layout: even-horizontal
      panes:
        - ui:
          - make ui
        - jobs-web:
          - make jobs-web

  - agent:
      panes:
        - agent:
          - make agent

  - control:
      panes:
        - control:
          - clear
